spring:
  application:
    name: tvmaze

  # CONECCION A MONGO BD
  mongodb:
    uri:

logging:
  level:
    com:
      hrr:
        tvmaze: DEBUG
    org:
      springframework:
        web: DEBUG
        data:
          mongodb: DEBUG